import Head from "next/head";
import React from "react";

function Layout({ children }) {
  return (
    <div className="all">
      <Head>
        <title>Users lists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children} </main>
      <style jsx>
        {`
          .all {
            padding: 20px;
          }
        `}
      </style>
    </div>
  );
}

export default Layout;
